In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [9]:
# write your code here ^_^
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [11]:
# write your code here ^_^
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [13]:
# write your code here ^_^
x + y

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [24]:
# write your code here ^_^
print(f"dimension = {x.ndim}")
print(f"shape = {x.shape}")
print(f"size = {x.size}")
print(f"type = {x.dtype}")

dimension = 1
shape = (5,)
size = 5
type = float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [32]:
# write your code here ^_^
w = np.arange(11,17)
w.reshape((3,2))

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [36]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [40]:
# write your code here ^_^
newArray = np.hstack((z,w))
newArray

array([ 1,  2,  3, 11, 12, 13, 14, 15, 16])

## Q#8: Print all elements of "newArray" using the loop.

In [42]:
# write your code here ^_^
for i in newArray:
    print(i)

1
2
3
11
12
13
14
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [75]:
# write your code here ^_^
newArray = np.flip(newArray)
newArray

array([16, 15, 14, 13, 12, 11,  3,  2,  1])

## Q#10: Decrement all elements of "newArray" with 1.

In [77]:
# write your code here ^_^
newArray = newArray - 1
newArray

array([15, 14, 13, 12, 11, 10,  2,  1,  0])

## Q#11: Find smallest and biggest values in "newArray".

In [79]:
# write your code here ^_^
print(f"smallest value = {newArray.min()}")
print(f"biggest value = {newArray.max()}")

smallest value = 0
biggest value = 15


## Q#12: Print the first row of "newArray" using indexing.

In [87]:
# write your code here ^_^
newArray[:]

array([15, 14, 13, 12, 11, 10,  2,  1,  0])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [109]:
# write your code here ^_^
newArray[newArray == 12]

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [115]:
# write your code here ^_^
newArray[(newArray == 0) | (newArray == 13)]

array([13,  0])

## Q#15: Change the shape of "newArray" to (9,1).

In [125]:
# write your code here ^_^
newArray.reshape((9,1))

array([[15],
       [14],
       [13],
       [12],
       [11],
       [10],
       [ 2],
       [ 1],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,2).

In [127]:
# write your code here ^_^
newArray.reshape((3,3)) # the shape (3,2) is not possible because we have 9 elements

array([[15, 14, 13],
       [12, 11, 10],
       [ 2,  1,  0]])

# Well Done 🎉